# Generated by Django 5.0.2 on 2025-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="required_fields",
            field=models.JSONField(
                default=list, help_text="List of required fields for this service"
            ),
        ),
    ]
