# Generated by Django 5.0.2 on 2025-04-28 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service_required_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RenameField(
            model_name="document",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="document",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="consultation",
            name="additional_documents",
            field=models.FileField(
                blank=True, null=True, upload_to="consultation_documents/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="business_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="consultation_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="current_challenges",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="financial_year",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="goals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="number_of_employees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="supporting_documents",
            field=models.FileField(
                blank=True, null=True, upload_to="consultation_documents/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="tax_year",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="If true, only admin and assigned consultant can view",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.service",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.consultation",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="service_documents/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
