# Generated by Django 5.0.2 on 2025-04-28 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_consultant_to_consultation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="required_fields",
        ),
        migrations.AddField(
            model_name="consultation",
            name="ai_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="ai_keywords",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="ai_priority",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="ai_recommendations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="ai_sentiment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("supporting", "Supporting Document"),
                    ("additional", "Additional Document"),
                    ("report", "Report"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="business_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="consultation_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="mode",
            field=models.CharField(
                choices=[("in_person", "In Person"), ("virtual", "Virtual")],
                default="virtual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="document",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.consultation",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="document",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.service",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="consultant_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="consultant_rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.consultation"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="service_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="service_rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(help_text="Duration in minutes"),
        ),
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="core.consultation",
                    ),
                ),
            ],
        ),
    ]
