# Generated by Django 5.0.2 on 2025-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_document_options_alter_service_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(default=60, help_text="Duration in minutes"),
        ),
    ]
